# ワークフロー名
name: test_chatbot

on:
#  schedule:
 #   - cron: '5 10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

     # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install line-bot-sdk
          pip install pandas
      - name: Run script
        run: |
          # main.pyの実行
          python3 main.py
